### ISSUE TITLE
Nuget package name is not equal to repository name

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/BriX#14]
### Expected Behavior
The name of the nuget package is equal to the ropository name

### Actual Behavior
Repository name: Brix
Nuget package name: Yaapii.Brix

### Mention any other details that might be useful
Namespace of `IBrix` is `Yaapii.Brix`

### The log given by the failure.

**Comment by aveXcaesar** [comment]
Which name is preferred?

**Comment by HerickJ-22** [comment]
I can't confirm this Issue. 
The nugetpackage name on nuget.org is BriX and not Yaapii.Brix: https://www.nuget.org/packages/BriX/
And the namespace of IBrix in the current master is [namespace BriX](https://github.com/icarus-consulting/BriX/blob/aecb9e3c264bc1ad1c4aea740e80863ba16fd283/src/BriX/IBrix.cs#L25)

**Comment by aveXcaesar** [comment]
Now I have noticed that we have Brix twice. One version on nuget.org and one in our internal nuget feed. I'm going to clean it up. The version on nuget.org is fine!
